utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

mega_casting:
    resource: "@MegaCastingBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"