<?php

namespace MegaCastingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * contratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contratRepository extends EntityRepository
{
}
