<?php

namespace MegaCastingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * offreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offreRepository extends EntityRepository
{
}
