<?php

namespace MegaCastingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCompetenceRepository extends EntityRepository
{
}
