services:
#    mega_casting.example:
#        class: MegaCastingBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    acme_user.registration.form.type:
        class: MegaCastingBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: acme_user_registration }